#ifndef _INTERRUPT_H
#define _INTERRUPT_H

typedef enum interrupt_vector {
  INT_DIVIDE_ERROR = 0,
  INT_NMI = 2,
  INT_BREAKPOINT = 3,
  INT_OVERFLOW = 4,
  INT_BOUND_RANGE = 5,
  INT_INVALID_OPCODE = 6,
  INT_NO_MATH = 7,
  INT_DOUBLE_FAULT = 8,
  INT_INVALID_TSS = 10,
  INT_NO_SEGMENT = 11,
  INT_SS_FAULT = 12,
  INT_GP_FAULT = 13,
  INT_PAGE_FAULT = 14,
  INT_MATH_FAULT = 16,
  INT_ALIGN_CHECK = 17,
  INT_MACHINE_CHECK = 18,
  INT_SIMD_FAULT = 19,
  INT_EXTERNAL_FIRST = 32,
  INT_EXTERNAL_LAST = 255,
} interrupt_vector_t;

#define IDT_SIZE (INT_EXTERNAL_LAST+1)

void init_interrupts();

#endif /* _INTERRUPT_H */
