#ifndef _BOOT_H
#define _BOOT_H

#define MULTIBOOT_ALIGN_PAGE 1<<0
#define MULTIBOOT_MEM_INFO 1<<1
#define MULTIBOOT_VIDEO_INFO 1<<2
#define MULTIBOOT_INTERNAL_RELOC 1<<16

#define MULTIBOOT_MAGIC 0x1BADB002
#define MULTIBOOT_FLAGS MULTIBOOT_ALIGN_PAGE | MULTIBOOT_MEM_INFO | MULTIBOOT_INTERNAL_RELOC
#define MULTIBOOT_CHECKSUM -(MULTIBOOT_MAGIC + MULTIBOOT_FLAGS)

#define STACK_SIZE 0x4000

#endif /* _BOOT_H */
